### ISSUE TITLE
Request to Create a New Tag for webpa-common and update Talaria with the latest webpa-common tag

### ISSUE THREAD

**Issue by chaitanyasingla-dt** [xmidt-org/webpa-common#1078]
The changes introduced in [Pull Request #439](https://github.com/xmidt-org/webpa-common/pull/439/files) were successfully merged into the master branch. However, these changes are not present in the latest tag for the webpa-common repository.

Request:
Please create a new tag for the webpa-common repository that includes the changes from [Pull Request #439](https://github.com/xmidt-org/webpa-common/pull/439/files).
Ensure that the latest changes from webpa-common, including [Pull Request #439](https://github.com/xmidt-org/webpa-common/pull/439/files), are integrated into Talaria.
Create a new tag for Talaria with the updated dependency on the latest webpa-common version.

**Comment by denopink** [comment]
done

https://github.com/xmidt-org/webpa-common/releases/tag/v2.4.3
https://github.com/xmidt-org/talaria/releases/tag/v0.12.0

**Comment by chaitanyasingla-dt** [comment]
Hi @denopink 
The changes are still not present in the latest webpa-common tag you created.
Can you please check?

**Comment by denopink** [comment]
@diogoViana95 @chaitanyasingla-dt looks like https://github.com/xmidt-org/webpa-common/pull/439 was merged into the wrong branch.

Please use `main` as the base and not `master`, `master` is no longer used in many (if not all) of repos 🙂

**Comment by denopink** [comment]
Create a new pr with `main` as the base and I'll review it as soon as I can and I'll re-release.

Closing this issue.
